from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent
CONFIG_LOAD_FROM = "templates"
CONFIG_LAYOUT_NAME = "_layout.html"
TEMPLATE_PATH =  BASE_DIR / CONFIG_LOAD_FROM
STATIC_NAME = 'static'
MEDIA_NAME = 'media'
DESTINATION_NAME = 'dist'

STATIC_ROOT = str(BASE_DIR / CONFIG_LOAD_FROM / STATIC_NAME)
MEDIA_ROOT = str(BASE_DIR / CONFIG_LOAD_FROM / MEDIA_NAME)

BUILD_ROOT = str(BASE_DIR / DESTINATION_NAME ) 
BUILD_STATIC_ROOT = str(BASE_DIR / DESTINATION_NAME / STATIC_NAME ) 
BUILD_MEDIA_ROOT = str(BASE_DIR / DESTINATION_NAME / MEDIA_NAME ) 
